package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func migrationCreateMoviesAndGenres() *gormigrate.Migration {
	return &gormigrate.Migration{
		ID: "202609090004",
		Migrate: func(tx *gorm.DB) error {
			return execAll(tx,
				`CREATE TABLE IF NOT EXISTS movies (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					slug TEXT NOT NULL,
					title TEXT NOT NULL,
					original_title TEXT,
					description TEXT,
					duration_min INT NOT NULL,
					age_rating age_rating NOT NULL,
					language TEXT,
					director TEXT,
					cast_members JSONB,
					poster_url TEXT,
					backdrop_url TEXT,
					trailer_url TEXT,
					release_date DATE NOT NULL,
					status movie_status NOT NULL DEFAULT 'coming_soon',
					deleted_at TIMESTAMPTZ,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT movies_slug_key UNIQUE (slug),
					CONSTRAINT movies_duration_min_check CHECK (duration_min > 0)
				)`,
				`CREATE INDEX IF NOT EXISTS movies_title_trgm_idx ON movies USING gin (title gin_trgm_ops)`,
				`CREATE TABLE IF NOT EXISTS genres (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					name TEXT NOT NULL,
					slug TEXT NOT NULL,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT genres_name_key UNIQUE (name),
					CONSTRAINT genres_slug_key UNIQUE (slug)
				)`,
				`CREATE TABLE IF NOT EXISTS movie_genres (
					movie_id BIGINT NOT NULL,
					genre_id BIGINT NOT NULL,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					PRIMARY KEY (movie_id, genre_id),
					CONSTRAINT movie_genres_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE,
					CONSTRAINT movie_genres_genre_id_fkey FOREIGN KEY (genre_id) REFERENCES genres (id)
				)`,
				`CREATE INDEX IF NOT EXISTS movie_genres_genre_id_idx ON movie_genres (genre_id)`,
			)
		},
		Rollback: func(tx *gorm.DB) error {
			return execAll(tx,
				`DROP TABLE IF EXISTS movie_genres`,
				`DROP TABLE IF EXISTS genres`,
				`DROP TABLE IF EXISTS movies`,
			)
		},
	}
}
