package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func migrationCreateBookingsAndTickets() *gormigrate.Migration {
	return &gormigrate.Migration{
		ID: "202609090007",
		Migrate: func(tx *gorm.DB) error {
			return execAll(tx,
				`CREATE TABLE IF NOT EXISTS bookings (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					code TEXT NOT NULL,
					user_id BIGINT NOT NULL,
					showtime_id BIGINT NOT NULL,
					status booking_status NOT NULL DEFAULT 'pending',
					subtotal NUMERIC(12,2) NOT NULL,
					discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
					currency CHAR(3) NOT NULL DEFAULT 'USD',
					expires_at TIMESTAMPTZ,
					confirmed_at TIMESTAMPTZ,
					note TEXT,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT bookings_code_key UNIQUE (code),
					CONSTRAINT bookings_id_showtime_id_key UNIQUE (id, showtime_id),
					CONSTRAINT bookings_subtotal_check CHECK (subtotal >= 0),
					CONSTRAINT bookings_discount_amount_check CHECK (discount_amount >= 0 AND discount_amount <= subtotal),
					CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id),
					CONSTRAINT bookings_showtime_id_fkey FOREIGN KEY (showtime_id) REFERENCES showtimes (id)
				)`,
				`CREATE INDEX IF NOT EXISTS bookings_user_id_created_at_idx ON bookings (user_id, created_at DESC)`,
				`CREATE INDEX IF NOT EXISTS bookings_pending_expires_at_idx ON bookings (expires_at) WHERE status = 'pending'`,
				`CREATE INDEX IF NOT EXISTS bookings_showtime_id_idx ON bookings (showtime_id)`,
				`CREATE TABLE IF NOT EXISTS tickets (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					booking_id BIGINT NOT NULL,
					showtime_id BIGINT NOT NULL,
					seat_id BIGINT NOT NULL,
					price NUMERIC(12,2) NOT NULL,
					status ticket_status NOT NULL DEFAULT 'held',
					qr_code UUID NOT NULL DEFAULT gen_random_uuid(),
					checked_in_at TIMESTAMPTZ,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT tickets_price_check CHECK (price >= 0),
					CONSTRAINT tickets_qr_code_key UNIQUE (qr_code),
					CONSTRAINT tickets_booking_id_showtime_id_fkey FOREIGN KEY (booking_id, showtime_id) REFERENCES bookings (id, showtime_id),
					CONSTRAINT tickets_showtime_id_fkey FOREIGN KEY (showtime_id) REFERENCES showtimes (id),
					CONSTRAINT tickets_seat_id_fkey FOREIGN KEY (seat_id) REFERENCES seats (id)
				)`,
				`CREATE UNIQUE INDEX IF NOT EXISTS tickets_one_active_per_seat ON tickets (showtime_id, seat_id) WHERE status IN ('held', 'paid')`,
				`CREATE INDEX IF NOT EXISTS tickets_booking_id_idx ON tickets (booking_id)`,
				`CREATE INDEX IF NOT EXISTS tickets_seat_id_idx ON tickets (seat_id)`,
			)
		},
		Rollback: func(tx *gorm.DB) error {
			return execAll(tx,
				`DROP TABLE IF EXISTS tickets`,
				`DROP TABLE IF EXISTS bookings`,
			)
		},
	}
}
