package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func migrationCreateTheatersRoomsSeats() *gormigrate.Migration {
	return &gormigrate.Migration{
		ID: "202609090005",
		Migrate: func(tx *gorm.DB) error {
			return execAll(tx,
				`CREATE TABLE IF NOT EXISTS theaters (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					slug TEXT NOT NULL,
					name TEXT NOT NULL,
					address TEXT NOT NULL,
					city TEXT NOT NULL,
					phone TEXT,
					description TEXT,
					image_url TEXT,
					is_active BOOLEAN NOT NULL DEFAULT true,
					deleted_at TIMESTAMPTZ,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT theaters_slug_key UNIQUE (slug)
				)`,
				`CREATE TABLE IF NOT EXISTS rooms (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					theater_id BIGINT NOT NULL,
					name TEXT NOT NULL,
					is_active BOOLEAN NOT NULL DEFAULT true,
					deleted_at TIMESTAMPTZ,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT rooms_theater_id_name_key UNIQUE (theater_id, name),
					CONSTRAINT rooms_theater_id_fkey FOREIGN KEY (theater_id) REFERENCES theaters (id)
				)`,
				`CREATE TABLE IF NOT EXISTS seat_types (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					code TEXT NOT NULL,
					name TEXT NOT NULL,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT seat_types_code_key UNIQUE (code)
				)`,
				`CREATE TABLE IF NOT EXISTS seats (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					room_id BIGINT NOT NULL,
					row_label TEXT NOT NULL,
					seat_number SMALLINT NOT NULL,
					seat_type_id BIGINT NOT NULL,
					is_active BOOLEAN NOT NULL DEFAULT true,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT seats_seat_number_check CHECK (seat_number > 0),
					CONSTRAINT seats_room_id_row_label_seat_number_key UNIQUE (room_id, row_label, seat_number),
					CONSTRAINT seats_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms (id),
					CONSTRAINT seats_seat_type_id_fkey FOREIGN KEY (seat_type_id) REFERENCES seat_types (id)
				)`,
			)
		},
		Rollback: func(tx *gorm.DB) error {
			return execAll(tx,
				`DROP TABLE IF EXISTS seats`,
				`DROP TABLE IF EXISTS seat_types`,
				`DROP TABLE IF EXISTS rooms`,
				`DROP TABLE IF EXISTS theaters`,
			)
		},
	}
}
