package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func migrationCreateShowtimesAndPrices() *gormigrate.Migration {
	return &gormigrate.Migration{
		ID: "202609090006",
		Migrate: func(tx *gorm.DB) error {
			return execAll(tx,
				`CREATE TABLE IF NOT EXISTS showtimes (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					movie_id BIGINT NOT NULL,
					room_id BIGINT NOT NULL,
					starts_at TIMESTAMPTZ NOT NULL,
					ends_at TIMESTAMPTZ NOT NULL,
					format showtime_format NOT NULL DEFAULT '2D',
					status showtime_status NOT NULL DEFAULT 'scheduled',
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT showtimes_ends_at_check CHECK (ends_at > starts_at),
					CONSTRAINT showtimes_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES movies (id),
					CONSTRAINT showtimes_room_id_fkey FOREIGN KEY (room_id) REFERENCES rooms (id),
					CONSTRAINT showtimes_no_overlap EXCLUDE USING gist (room_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status = 'scheduled')
				)`,
				`CREATE INDEX IF NOT EXISTS showtimes_movie_id_starts_at_idx ON showtimes (movie_id, starts_at)`,
				`CREATE INDEX IF NOT EXISTS showtimes_room_id_starts_at_idx ON showtimes (room_id, starts_at)`,
				`CREATE TABLE IF NOT EXISTS showtime_prices (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					showtime_id BIGINT NOT NULL,
					seat_type_id BIGINT NOT NULL,
					price NUMERIC(12,2) NOT NULL,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					CONSTRAINT showtime_prices_price_check CHECK (price >= 0),
					CONSTRAINT showtime_prices_showtime_id_seat_type_id_key UNIQUE (showtime_id, seat_type_id),
					CONSTRAINT showtime_prices_showtime_id_fkey FOREIGN KEY (showtime_id) REFERENCES showtimes (id) ON DELETE CASCADE,
					CONSTRAINT showtime_prices_seat_type_id_fkey FOREIGN KEY (seat_type_id) REFERENCES seat_types (id)
				)`,
			)
		},
		Rollback: func(tx *gorm.DB) error {
			return execAll(tx,
				`DROP TABLE IF EXISTS showtime_prices`,
				`DROP TABLE IF EXISTS showtimes`,
			)
		},
	}
}
