package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func migrationCreateUsers() *gormigrate.Migration {
	return &gormigrate.Migration{
		ID: "202609090003",
		Migrate: func(tx *gorm.DB) error {
			return execAll(tx,
				`CREATE TABLE IF NOT EXISTS users (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					email TEXT NOT NULL,
					password_hash TEXT NOT NULL,
					full_name TEXT NOT NULL,
					phone TEXT,
					date_of_birth DATE,
					avatar_url TEXT,
					role user_role NOT NULL DEFAULT 'user',
					email_verified_at TIMESTAMPTZ,
					last_login_at TIMESTAMPTZ,
					deleted_at TIMESTAMPTZ,
					created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
					updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
				)`,
				`CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_key ON users (lower(email))`,
			)
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Exec(`DROP TABLE IF EXISTS users`).Error
		},
	}
}
